<?php
if (!function_exists('following_to_user')) {
	function following_to_user($user_id) {
		$CI =& get_instance();
		$loggedin_user_id = $CI->session->userdata('user_id');

		$following = $CI->db->get_where('followers', ['user_id' => $loggedin_user_id, 'follower_id' => $user_id])->row();
		if (is_null($following)) {
			return FALSE;
		}
		return TRUE;
	}
}

if (!function_exists('set_json_response')) {
	function set_json_response($data) {
		header('Content-Type: application/json');
		echo json_encode($data);
		exit;
	}
}

if (!function_exists('send_sms')) {
function send_sms($data="")
{

  //print_r($data); die;
  $message=$data['message']; //$data['otp']." is the OTP to SignUp on PartyPeople .Do not share to anyone.";
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/


//Your authentication key
$authKey = "102856ABHD5nwUDlW569f0261";

//Multiple mobiles numbers separated by comma
$mobileNumber =$data['mobile_nuber'];

//Sender ID,While using route4 sender id should be 6 characters long.
$senderId = "PRTYPP";

//Your message to send, Add URL encoding here.
$message = urlencode($message);

//Define route 
$route = "4";
//Prepare you post parameters
$DLT_TE_ID=$data['template_id']; // "1207167508255462029"; //template id provide
$postData = array(
    'authkey' => $authKey,
    'mobiles' => $mobileNumber,
    'message' => $message,
    'sender' => $senderId,
    'route' => $route,
    'DLT_TE_ID'=>$DLT_TE_ID
);

//API URL
$url="http://api.msg91.com/api/sendhttp.php";

// init the resource
$ch = curl_init();
curl_setopt_array($ch, array(
    CURLOPT_URL => $url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => $postData
    //,CURLOPT_FOLLOWLOCATION => true
));

//Ignore SSL certificate verification
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

//get response
$output = curl_exec($ch);

//Print error if any
if(curl_errno($ch))
{
    //echo 'error:' . curl_error($ch);
  return 0;
}else{
  return 1;
}
curl_close($ch);
//echo $output;
}

}

if (!function_exists('get_otp')) {
function get_otp($length = 10) 
{
    $number = random_int(0,9999);
    $number = str_pad($number,4, 0, STR_PAD_LEFT);
    return $number;
  
}
}

/*---------------------Comma separated validation----------------*/
function check_comma_separated_value($comma_separated_val)
{
  
        $value=$comma_separated_val;
        $array=explode(',',$value);
        krsort($array);
        if(!empty($array))
        {
            foreach ($array as $key => $val) {
               if(empty($val))
               {
                return true;
                exit();
               }
            }
        }
}
?>